version: "3"
services:
  octopus:
    image: node:11.10
    volumes:
      - .:/app
    networks:
      - traefik
      - podcloud
      - default
    working_dir: /app
    ports:
        - 3000
    labels:
        traefik.port: 3000
        traefik.frontend.rule: "Host:kraken.podcloud.test"
        traefik.frontend.priority: 500
    depends_on:
        - kraken_db
        - storage_one
        - storage_two
        - storage_three
        - storage_four
    command: npm start

  kraken_db:
    image: mongo:4.0
    networks:
      - default
      - podcloud
    volumes:
      - ./support/mongo/data/db:/data/db
      - ./support/mongo/dump:/dump
    environment:
      - AUTH=false
    labels:
      - traefik.enable:false

  storage_one:
    image: kraken-storage-node
    build: ./support/storages
    volumes:
      - ./support/storages/one/data:/home/data
      - ./support/storages/one/id_rsa.pub:/home/data/.ssh/keys/id_rsa.pub:ro
    ports:
      - 22
    networks:
      - podcloud
      - default
    labels:
      traefik.enable: false

  storage_two:
    image: kraken-storage-node
    volumes:
      - ./support/storages/two/data:/home/data
      - ./support/storages/two/id_rsa.pub:/home/data/.ssh/keys/id_rsa.pub:ro
    ports:
      - 22
    networks:
      - podcloud
      - default
    labels:
      traefik.enable: false

  storage_three:
    image: kraken-storage-node
    volumes:
      - ./support/storages/three/data:/home/data
      - ./support/storages/three/id_rsa.pub:/home/data/.ssh/keys/id_rsa.pub:ro
    ports:
      - 22
    networks:
      - podcloud
      - default
    labels:
      traefik.enable: false

  storage_four:
    image: kraken-storage-node
    volumes:
      - ./support/storages/four/data:/home/data
      - ./support/storages/four/id_rsa.pub:/home/data/.ssh/keys/id_rsa.pub:ro
    ports:
      - 22
    networks:
      - podcloud
      - default
    labels:
      traefik.enable: false

networks:
  podcloud:
    external: true
  traefik:
    external: true
