version: "3"
services:
  octopus:
    image: node:11.10
    volumes:
      - .:/app
    networks:
      - traefik
      - podcloud
      - default
    working_dir: /app
    ports:
        - 3000
    labels:
        traefik.port: 3000
        traefik.frontend.rule: "Host:kraken.podcloud.test"
        traefik.frontend.priority: 500
    command: npm start

  mongo:
    image: mongo:4.0
    networks:
      - default
      - podcloud
    volumes:
      - ./support/mongo/data/db:/data/db
      - ./support/mongo/dump:/dump
    environment:
      - AUTH=false
    labels:
      - traefik.enable:false

  storage_one:
    image: atmoz/sftp:alpine-3.7
    volumes:
      - ./support/storages/one/data:/home/data
      - ./support/storages/one/id_rsa.pub:/home/data/.ssh/keys/id_rsa.pub:ro
      - ./support/storages/create_files_dir.sh:/etc/sftp.d/create_files_dir.sh
    networks:
      - podcloud
      - default
    labels:
      traefik.enable: false
    command: data::1001

  storage_two:
    image: atmoz/sftp:alpine-3.7
    volumes:
      - ./support/storages/two/data:/home/data
      - ./support/storages/two/id_rsa.pub:/home/data/.ssh/keys/id_rsa.pub:ro
      - ./support/storages/create_files_dir.sh:/etc/sftp.d/create_files_dir.sh
    networks:
      - podcloud
      - default
    labels:
      traefik.enable: false
    command: data::1001

  storage_three:
    image: atmoz/sftp:alpine-3.7
    volumes:
      - ./support/storages/three/data:/home/data
      - ./support/storages/three/id_rsa.pub:/home/data/.ssh/keys/id_rsa.pub:ro
      - ./support/storages/create_files_dir.sh:/etc/sftp.d/create_files_dir.sh
    networks:
      - podcloud
      - default
    labels:
      traefik.enable: false
    command: data::1001

  storage_four:
    image: atmoz/sftp:alpine-3.7
    volumes:
      - ./support/storages/four/data:/home/data
      - ./support/storages/four/id_rsa.pub:/home/data/.ssh/keys/id_rsa.pub:ro
      - ./support/storages/create_files_dir.sh:/etc/sftp.d/create_files_dir.sh
    networks:
      - podcloud
      - default
    labels:
      traefik.enable: false
    command: data::1001

networks:
  podcloud:
    external: true
  traefik:
    external: true
